export const projects = [
  {
    id: 1,
    title: "Notionary",
    img: "/Notionary.png",
    tools: [
      "TypeScript",
      "React",
      "MongoDB",
      "Express",
      "Node.js",
      "Tailwind CSS",
    ],
    description: [
      "Built a full-stack application for creating and managing notes and tasks.",
      "Developed backend functionality to handle note creation, categorization, and management.",
      "Designed an intuitive interface for easy note organization and retrieval.",
      "Incorporated features for editing, deleting, and organizing notes by category.",
    ],
    sourceCode: "https://github.com/TahaZoabi/Notionary",
    liveDemo: "https://notionary.netlify.app/",
  },
  {
    id: 2,
    title: "BlogFlow",
    img: "/BlogFlow.png",
    tools: ["Vite", "TypeScript", "Vue js", "Tailwind CSS"],
    description: [
      "Developed a frontend application for browsing and filtering blog posts by category.",
      "Implemented a search feature for users to find specific blog posts quickly.",
      "Created a visually appealing interface with detailed blog post pages.",
      "Designed with user-centric navigation for an enhanced browsing experience.",
    ],
    sourceCode: "https://github.com/TahaZoabi/BlogFlow",
    liveDemo: "https://blog-flow-mocha.vercel.app",
  },
  {
    id: 3,
    title: "Portfolio",
    img: "/Portfolio.png",
    tools: ["Vite", "TypeScript", "Vue js", "Tailwind CSS"],
    description: [
      "Built a personal portfolio website to showcase key projects and achievements.",
      "Designed a clean, modern layout with easy navigation between sections.",
      "Focused on presenting work in a visually appealing and accessible way.",
      "Optimized the website for responsiveness and a seamless mobile experience.",
    ],
    sourceCode: "https://github.com/TahaZoabi/TahaZoabi.com",
    liveDemo: "https://www.tahazoabi.com/",
  },
  {
    id: 4,
    title: "Forecastly",
    img: "/Forecastly.png",
    tools: ["Vite", "TypeScript", "Vue js", "Tailwind CSS", "WeatherAPI"],
    description: [
      "Engineered a weather application integrating WeatherAPI for real-time weather data and forecasts.",
      "Implemented geolocation services and city search functionality with TypeScript type safety.",
      "Developed responsive Vue components for displaying current weather conditions and 3-day forecasts.",
      "Built an intuitive user interface with error handling and seamless mobile responsiveness.",
    ],
    sourceCode: "https://github.com/TahaZoabi/Forecastly",
    liveDemo: "https://forecastly-tau.vercel.app/",
  },
];
